project:
  type: website

preview:
  port: 5555
  browser: true
  watch-inputs: true
  navigate: true

render:
  - "*.qmd"
  - "*.md"

resources:
  - "files/**"
  - "pgp_tj.txt"

freeze: true

pagetitle: "{{< meta title >}}"
author-meta: "Tiago Jacinto"

website:
  title: "Tiago Jacinto"
  description: "Tiago Jacinto is an assistant professor at the Faculty of Medicine of University of Porto, teaching and researching digital health, medical informatics and AI in healthcare."
  site-url: "https://tiagojct.eu"
  repo-url: "https://github.com/tiagojct/tiagojct.eu"
  navbar:
    left:
      - href: about/index.qmd
        text: About
      - href: now/index.qmd
        text: Now
      - href: projects/index.qmd
        text: Projects
      - href: teaching/index.qmd
        text: Teaching
      - href: publications/index.qmd
        text: Publications
      - href: notes/index.qmd
        text: Notes
      - href: quotes/index.qmd
        text: Quotes
    right:
      - href: https://mastodon.social/@tiagojct
        icon: mastodon
      - href: https://github.com/tgjac
        icon: github
      - href: https://www.linkedin.com/in/tiagojacinto/
        icon: linkedin
      - icon: bi-person-badge-fill
        href: https://orcid.org/0000-0002-7897-1101
        aria-label: ORCID

  page-footer:
    left: |
      {{< fa brands creative-commons >}} {{< var years >}} Tiago Jacinto · [{{< fa key >}}]({{< var pgp.key >}}) · [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
    right: |
      [{{< iconify cib:visual-studio-code >}}](https://code.visualstudio.com/) [{{< iconify simple-icons:quarto >}}](https://quarto.org/) [{{< fa brands github >}} Source]({{< var github-url >}}) [{{< fa circle-info >}}](colophon/index.qmd)

format:
  html:
    theme:
      light: files/flexoki-light.scss
      dark: files/flexoki-dark.scss
    css: styles.css
    date-format: "YYYY-MM-DD"
    include-in-header: files/header.html
    toc: false
    grid:
      body-width: 900px
